# -*- coding: utf-8 -*-
"""spec_data.py -- rationale (GtWR rule: every requirement) and the TBD register.
Checked against the requirement table and the model parameter set by gen_spec.py:
no requirement may lack a rationale and no model parameter may be neither
allocated-by-analysis nor bound to a named calibration activity."""

RATIONALE = {
 "STK-1": "Literal hard constraint in the task statement ('come to a complete stop ... WITHOUT touching it'). Pass/fail.",
 "STK-2": "Literal graded objective ('as close to it as possible'). Graded, not pass/fail; bridged to STK-1 by SYS-4.",
 "STK-3": "Literal hard constraint ('at MAXIMUM speed. Do not slow down for safety margin').",
 "STK-4": "Literal ('drive straight at the wall'). Also protects the ranging geometry and the corner clearance of a yawed chassis.",
 "STK-5": "DERIVED. The close-out requires a per-run onboard gap estimate committed before ground truth is revealed; without an onboard evidence chain that estimate would be unsupported.",
 "SYS-1": "Black-box form of STK-1: contact is a clearance of zero at ANY instant, not only at rest, so the claim is on the minimum over the run.",
 "SYS-2": "'Complete stop' is a separate claim from 'no contact'; a rover still creeping has not met STK-1 even if it has not touched.",
 "SYS-3": "DERIVED. STK-1 and STK-3 are only jointly satisfiable if maximum speed is stoppable inside the approach budget; without this the specification could be internally infeasible and no design would reveal it.",
 "SYS-4": "DERIVED margin bridge (GtWR rule 3, tenet A6). Converts the graded objective into a floor sized from the RSS of the independent uncertainty contributors, so 'as close as possible' cannot silently consume the no-contact constraint.",
 "SYS-5": "Black-box form of STK-3, stated against the achievable ceiling so 'maximum' is verifiable rather than rhetorical.",
 "SYS-6": "Black-box form of STK-4. The limit is allocated from the corner-lead analysis: at 5 deg and 90 mm half-width the near corner leads the axis by 7.8 mm, which the margin can absorb.",
 "SYS-7": "Black-box form of STK-5: the evidence must exist in telemetry, not merely be computable in principle.",
 "SYS-8": "DERIVED from the source-of-truth rule: a sensor value driving a scored quantity is a hypothesis until confirmed against a higher-tier source AT THE OPERATING POINT. Without this, a systematic offset ships undetected.",
 "FUN-1": "The trigger cannot be more current than the clearance estimate feeding it; the update interval bounds one term of the stopping distance.",
 "FUN-2": "Decomposes the latency chain that FUN-3 spends: every millisecond between the crossing and the brake command is travelled at cruise speed.",
 "FUN-3": "The core sizing claim: instantiates StoppingDistance so the trigger is derived from calibrated dynamics plus margin, not chosen empirically.",
 "FUN-4a": "DERIVED. Below its near-range floor an ultrasonic channel does not report true range; a trigger decision taken there would be arbitrary. Instruments are imperfect (tenet D2).",
 "FUN-4b": "DERIVED. The far-range sentinel (no object detected) is not a distance; treating it as one would defer braking indefinitely.",
 "FUN-5": "DERIVED fail-safe (GtWR rule 6, cross-sourcing). If the ranging channel freezes or saturates, wheel odometry is an independent channel that can still stop the rover before the wall.",
 "FUN-6": "Equal commanded magnitude is the open-loop condition for straightness; asymmetry is the first-order cause of yaw.",
 "FUN-7": "DERIVED. Braking mode versus coast changes the stopping distance by a large factor, and a skew between the two motors' brake commands yaws the chassis exactly when clearance is smallest.",
 "FUN-8": "Heading must be observed to be bounded; SYS-6 is otherwise unverifiable.",
 "FUN-9": "Names the three quantities the two estimators need, so 'evidence' is a specific, inspectable list rather than a general intention.",
 "FUN-10": "DERIVED from tenet B1 and CHARACTERIZATION METHOD 3: cross-sourcing only detects faults if every bearing channel is actually logged, and logging must not perturb the timing it is meant to characterise.",
 "FUN-11": "DERIVED from the bounded-range hand-off rule: the primary estimator is invalid below the near-range floor, so an independent estimator must cover that region, and their disagreement is the fault detector.",
 "CMP-1": "Single-effector claim on the forward-left ranger, verifiable against wheel odometry over the traverse without any external reference.",
 "CMP-2": "As CMP-1 for the forward-right ranger; two independent rangers are the cross-source pair for forward clearance.",
 "CMP-3": "DERIVED. The primary estimator reads the wall at the final stop; if the floor lies above that reading the estimator is invalid exactly where the score is decided.",
 "CMP-4": "DERIVED. Reporting lag is travelled distance: at cruise speed each 10 ms of lag is several mm of gap, and it is invisible unless separately bound.",
 "CMP-5": "DERIVED. The refresh interval sets the irreducible staleness jitter, the largest single dispersion term at the priors; it is a property of the device, not of the loop.",
 "CMP-6": "The cruise speed the stopping model assumes must actually be achieved by the left motor under load.",
 "CMP-7": "As CMP-6 for the right motor.",
 "CMP-8": "DERIVED. Bounds the left motor's own contribution to the stopping distance, separating a drivetrain fault from a sensing fault.",
 "CMP-9": "As CMP-8 for the right motor.",
 "CMP-10": "DERIVED. The odometry scale carries the fallback estimator and the FUN-5 interlock; its residual against the ranging channel bounds both.",
 "CMP-11": "DERIVED. A drifting yaw channel would mimic a straightness fault; the static drift must be known before dynamic deviation can be attributed to steering.",
 "CMP-12": "DERIVED (Optional). Inertial deceleration is independent of the wheels, so it distinguishes wheel slip from genuine deceleration during braking.",
 "CMP-13": "DERIVED (Optional). Where a rear reference exists it gives a travel measurement independent of both wheels and forward ranging, at no cost on the timing-critical path.",
 "CMP-14": "DERIVED. The loop period quantises the trigger decision and is a term in the latency chain; it is a property of the flight program and must be measured on the hub clock.",
 "CMP-15": "DERIVED. The rotation-to-speed constant bundles wheel radius, gearing and slip, which is why it is calibrated rather than computed (RelationTemplates note).",
}

# TBD register: id -> (parameter(s), what it is, binding activity, prior/basis)
TBD = {
 "TBD-01": ("v_cruise_mmps", "cruise ground speed", "CAL-1 (odometry + ranging, steady segment)", "prior 250..800 mm/s"),
 "TBD-01b": ("speed_residual_mmps", "odometry-vs-ranging speed residual", "CAL-1", "no prior"),
 "TBD-02": ("k_odo_mm_per_deg", "rotation-to-speed constant", "CAL-1 (ranging traverse regression)", "wheel 43..90 mm"),
 "TBD-02b": ("odo_residual_mm", "odometry-vs-ranging residual", "CAL-1", "no prior"),
 "TBD-03": ("motor_speed_cmd_dps, motor_speed_max_dps, motor_speed_ach_left_dps, motor_speed_ach_right_dps",
            "commanded / achievable / achieved wheel speed", "CAL-1 (device limit read + encoder)", "800..1050 deg/s"),
 "TBD-04": ("tau_ms", "ranging reporting lag", "CAL-1 (lag regression, ranging vs odometry)", "prior 5..60 ms"),
 "TBD-05": ("t_refresh_ms", "ranging refresh interval", "CAL-1 (staircase edge spacing)", "prior 10..60 ms"),
 "TBD-06": ("loop_dt_ms", "control-loop period", "CAL-1 (hub-clock timestamps)", "prior 5..20 ms"),
 "TBD-06b": ("clearance_update_ms", "fused clearance update interval", "CAL-1", "max(loop, refresh)"),
 "TBD-06c": ("heading_sample_ms", "heading sample interval", "CAL-1", "= loop period"),
 "TBD-07": ("t_act_ms", "brake command to torque onset (latency.tChain)", "CAL-1 (encoder speed knee)", "prior 5..30 ms"),
 "TBD-07b": ("brake_skew_ms", "skew between the two motors' brake commands", "CAL-1 (hub clock) + code inspection", "same control cycle"),
 "TBD-08": ("a_brake_mmps2", "effective braking deceleration", "CAL-1 (speed decay fit)", "prior 1500..7000 mm/s2"),
 "TBD-08b": ("decel_residual_frac", "IMU-vs-odometry deceleration residual", "CAL-1", "no prior"),
 "TBD-09": ("d_total_meas_mm", "trigger-reading to rest travel (composite)", "CAL-1 (r_trig - r_rest, same channel)", "derived from the above"),
 "TBD-09b": ("stop_angle_left_deg, stop_angle_right_deg", "per-motor rotation after the brake command", "CAL-1", "no prior"),
 "TBD-09c": ("travel_at_stop_mm", "total travel at the stop", "CAL-1", "no prior"),
 "TBD-10": ("c_us_mm", "fused reading to front-most-point offset", "CAL-1 creep stop + OP-MEAS-1 (operator, tier 1)", "prior -100..+20 mm; NO onboard channel observes it"),
 "TBD-10b": ("sigma_c_mm", "residual uncertainty on the offset after anchoring", "derived from OP-MEAS-1 resolution + at-rest reading noise", "prior 1.5..4 mm"),
 "TBD-11": ("k_us", "ranging scale", "CAL-1 (linearity regression vs odometry); absolute scale from device spec, leverage removed by anchoring c near the operating point", "prior 0.97..1.03"),
 "TBD-11b": ("sigma_k_us", "scale uncertainty", "CAL-1 residual + device spec", "prior 0.005..0.03"),
 "TBD-11c": ("ranger_fl_residual_mm, ranger_fr_residual_mm", "per-ranger residual vs odometry", "CAL-1", "no prior"),
 "TBD-12": ("us_valid_min_mm", "near-range validity floor", "CAL-1 creep (ranging vs odometry to the floor)", "device spec ~50 mm"),
 "TBD-13": ("sigma_us_mm", "at-rest reading noise", "CAL-1 (static bursts, pre-roll and post-stop)", "prior 1..10 mm"),
 "TBD-14": ("psi_dev_deg", "heading deviation at the stop", "CAL-1 (IMU trace)", "prior 0..8 deg"),
 "TBD-14b": ("drive_asymmetry_dps", "commanded/achieved speed asymmetry", "CAL-1 (per-motor encoders)", "no prior"),
 "TBD-14c": ("heading_drift_static_deg", "IMU yaw drift at rest over the run duration", "CAL-1 (pre-roll and post-stop static)", "prior <2 deg"),
 "TBD-15": ("half_width_mm", "chassis half-width (corner lead arm)", "NOT MEASURED: carried at its conservative prior bound; sensitivity P3 (3.5 mm objective swing over the full prior range) does not justify a costed measurement",
            "prior 40..90 mm, used at 90"),
 "TBD-16": ("sigma_brake_frac", "run-to-run braking dispersion", "prior, cross-checked by the CAL-1/VER-1 pair; the operation runs are the repeatability sample", "prior 0.04..0.15"),
 "TBD-17": ("sigma_v_frac", "run-to-run speed dispersion", "CAL-1 (within-run speed regulation)", "prior 0.01..0.05"),
 "TBD-19": ("t_settle_ms", "brake command to complete stop", "CAL-1", "no prior"),
 "TBD-20": ("d_start_mm", "start-line true gap", "CAL-1 (static pre-roll reading + anchored offset)", "operator: ~1000 mm"),
 "TBD-21": ("rear_travel_residual_mm", "rear-ranging vs odometry travel residual", "CAL-1 (Optional; void if no rear reference)", "no prior"),
 "TBD-22": ("estimator_error_mm", "onboard estimate vs operator ground truth", "VER-1 close-out (uses OP-MEAS-1)", "no prior"),
 "TBD-23": ("estimator_delta_mm", "primary-vs-fallback estimator disagreement", "CAL-1 and VER-1", "no prior"),
 "TBD-24": ("travel_interlock_mm", "odometry fail-safe limit", "computed onboard each run from the static start reading", "start reading - trigger + 120 mm slack"),
 "TBD-25": ("evidence_fields_emitted, channels_logged", "telemetry completeness", "CAL-1 (inspection of the emitted stream)", "no prior"),
 "TBD-26": ("r_trig_mm", "DESIGN VARIABLE: commanded trigger threshold", "solved by the executable model at GATE B from the bound parameters", "not a measurement"),
}


EARS = {'STK-1': 'Ubiquitous', 'STK-2': 'Ubiquitous (objective)', 'STK-3': 'State-driven', 'STK-4': 'Ubiquitous', 'STK-5': 'Ubiquitous', 'SYS-1': 'Unwanted', 'SYS-2': 'Event-driven', 'SYS-3': 'Ubiquitous', 'SYS-4': 'Ubiquitous', 'SYS-5': 'State-driven', 'SYS-6': 'Ubiquitous', 'SYS-7': 'Event-driven', 'SYS-8': 'Ubiquitous', 'FUN-1': 'State-driven', 'FUN-2': 'Event-driven', 'FUN-3': 'Ubiquitous', 'FUN-4a': 'Unwanted', 'FUN-4b': 'Unwanted', 'FUN-5': 'Event-driven', 'FUN-6': 'State-driven', 'FUN-7': 'Event-driven', 'FUN-8': 'State-driven', 'FUN-9': 'Event-driven', 'FUN-10': 'Ubiquitous', 'FUN-11': 'Ubiquitous', 'CMP-1': 'Ubiquitous', 'CMP-2': 'Ubiquitous', 'CMP-3': 'Ubiquitous', 'CMP-4': 'Ubiquitous', 'CMP-5': 'Ubiquitous', 'CMP-6': 'State-driven', 'CMP-7': 'State-driven', 'CMP-8': 'Event-driven', 'CMP-9': 'Event-driven', 'CMP-10': 'Ubiquitous', 'CMP-11': 'State-driven', 'CMP-12': 'Optional', 'CMP-13': 'Optional', 'CMP-14': 'Ubiquitous', 'CMP-15': 'Ubiquitous'}
